<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [
<!ENTITY Aacute           "&#x000C1;" >
<!ENTITY aacute           "&#x000E1;" >
<!ENTITY Acirc            "&#x000C2;" >
<!ENTITY acirc            "&#x000E2;" >
<!ENTITY acute            "&#x000B4;" >
<!ENTITY AElig            "&#x000C6;" >
<!ENTITY aelig            "&#x000E6;" >
<!ENTITY Agrave           "&#x000C0;" >
<!ENTITY agrave           "&#x000E0;" >
<!ENTITY Aring            "&#x000C5;" >
<!ENTITY aring            "&#x000E5;" >
<!ENTITY Atilde           "&#x000C3;" >
<!ENTITY atilde           "&#x000E3;" >
<!ENTITY Auml             "&#x000C4;" >
<!ENTITY auml             "&#x000E4;" >
<!ENTITY brvbar           "&#x000A6;" >
<!ENTITY Ccedil           "&#x000C7;" >
<!ENTITY ccedil           "&#x000E7;" >
<!ENTITY cedil            "&#x000B8;" >
<!ENTITY cent             "&#x000A2;" >
<!ENTITY copy             "&#x000A9;" >
<!ENTITY curren           "&#x000A4;" >
<!ENTITY deg              "&#x000B0;" >
<!ENTITY divide           "&#x000F7;" >
<!ENTITY Eacute           "&#x000C9;" >
<!ENTITY eacute           "&#x000E9;" >
<!ENTITY Ecirc            "&#x000CA;" >
<!ENTITY ecirc            "&#x000EA;" >
<!ENTITY Egrave           "&#x000C8;" >
<!ENTITY egrave           "&#x000E8;" >
<!ENTITY ETH              "&#x000D0;" >
<!ENTITY eth              "&#x000F0;" >
<!ENTITY Euml             "&#x000CB;" >
<!ENTITY euml             "&#x000EB;" >
<!ENTITY frac12           "&#x000BD;" >
<!ENTITY frac14           "&#x000BC;" >
<!ENTITY frac34           "&#x000BE;" >
<!ENTITY Iacute           "&#x000CD;" >
<!ENTITY iacute           "&#x000ED;" >
<!ENTITY Icirc            "&#x000CE;" >
<!ENTITY icirc            "&#x000EE;" >
<!ENTITY iexcl            "&#x000A1;" >
<!ENTITY Igrave           "&#x000CC;" >
<!ENTITY igrave           "&#x000EC;" >
<!ENTITY iquest           "&#x000BF;" >
<!ENTITY Iuml             "&#x000CF;" >
<!ENTITY iuml             "&#x000EF;" >
<!ENTITY laquo            "&#x000AB;" >
<!ENTITY macr             "&#x000AF;" >
<!ENTITY micro            "&#x000B5;" >
<!ENTITY middot           "&#x000B7;" >
<!ENTITY nbsp             "&#x000A0;" >
<!ENTITY not              "&#x000AC;" >
<!ENTITY Ntilde           "&#x000D1;" >
<!ENTITY ntilde           "&#x000F1;" >
<!ENTITY Oacute           "&#x000D3;" >
<!ENTITY oacute           "&#x000F3;" >
<!ENTITY Ocirc            "&#x000D4;" >
<!ENTITY ocirc            "&#x000F4;" >
<!ENTITY Ograve           "&#x000D2;" >
<!ENTITY ograve           "&#x000F2;" >
<!ENTITY ordf             "&#x000AA;" >
<!ENTITY ordm             "&#x000BA;" >
<!ENTITY Oslash           "&#x000D8;" >
<!ENTITY oslash           "&#x000F8;" >
<!ENTITY Otilde           "&#x000D5;" >
<!ENTITY otilde           "&#x000F5;" >
<!ENTITY Ouml             "&#x000D6;" >
<!ENTITY ouml             "&#x000F6;" >
<!ENTITY para             "&#x000B6;" >
<!ENTITY plusmn           "&#x000B1;" >
<!ENTITY pound            "&#x000A3;" >
<!ENTITY raquo            "&#x000BB;" >
<!ENTITY reg              "&#x000AE;" >
<!ENTITY sect             "&#x000A7;" >
<!ENTITY shy              "&#x000AD;" >
<!ENTITY sup1             "&#x000B9;" >
<!ENTITY sup2             "&#x000B2;" >
<!ENTITY sup3             "&#x000B3;" >
<!ENTITY szlig            "&#x000DF;" >
<!ENTITY THORN            "&#x000DE;" >
<!ENTITY thorn            "&#x000FE;" >
<!ENTITY times            "&#x000D7;" >
<!ENTITY Uacute           "&#x000DA;" >
<!ENTITY uacute           "&#x000FA;" >
<!ENTITY Ucirc            "&#x000DB;" >
<!ENTITY ucirc            "&#x000FB;" >
<!ENTITY Ugrave           "&#x000D9;" >
<!ENTITY ugrave           "&#x000F9;" >
<!ENTITY uml              "&#x000A8;" >
<!ENTITY Uuml             "&#x000DC;" >
<!ENTITY uuml             "&#x000FC;" >
<!ENTITY Yacute           "&#x000DD;" >
<!ENTITY yacute           "&#x000FD;" >
<!ENTITY yen              "&#x000A5;" >
<!ENTITY yuml             "&#x000FF;" >
<!ELEMENT root         (inputdata,prefixdata*,error*)>
<!ELEMENT error         (#PCDATA)>
<!ELEMENT inputdata    (npa?,nxx?,x?,exch?,rc?,region?,switch?,lata?,lir?,ocn?,blocks?,pastdays?,nextdays?,udate?)>
<!ELEMENT prefixdata   (npa,nxx,x,exch,udate,rc,region,switch,switchname,switchtype,lata,lir,ocn,company-name,ilec-ocn,ilec-name,rc-v,rc-h,rc-lat,rc-lon,effdate,discdate)>
<!ELEMENT npa          (#PCDATA)>
<!ELEMENT nxx          (#PCDATA)>
<!ELEMENT x            (#PCDATA)>
<!ELEMENT exch         (#PCDATA)>
<!ELEMENT udate        (#PCDATA)>
<!ELEMENT rc           (#PCDATA)>
<!ELEMENT region       (#PCDATA)>
<!ELEMENT switch       (#PCDATA)>
<!ELEMENT switchname   (#PCDATA)>
<!ELEMENT switchtype   (#PCDATA)>
<!ELEMENT lata         (#PCDATA)>
<!ELEMENT lir          (#PCDATA)>
<!ELEMENT ocn          (#PCDATA)>
<!ELEMENT company-name (#PCDATA)>
<!ELEMENT company-type (#PCDATA)>
<!ELEMENT ilec-ocn     (#PCDATA)>
<!ELEMENT ilec-name    (#PCDATA)>
<!ELEMENT rc-v         (#PCDATA)>
<!ELEMENT rc-h         (#PCDATA)>
<!ELEMENT rc-lat       (#PCDATA)>
<!ELEMENT rc-lon       (#PCDATA)>
<!ELEMENT effdate      (#PCDATA)>
<!ELEMENT discdate     (#PCDATA)>
]>
<root>
<inputdata>
<lata>472</lata>
</inputdata>
<prefixdata>
<npa>256</npa>
<nxx>437</nxx>
<x>A</x>
<exch>008980</exch>
<rc>Stevenson</rc>
<region>AL</region>
<switch>STSNALMADS1</switch>
<switchname>STEVENSON</switchname>
<switchtype>5E</switchtype>
<ocn>9419</ocn>
<company-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </company-name>
<company-type>I</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7176</rc-v>
<rc-h>2430</rc-h>
<rc-lat>34.869143</rc-lat>
<rc-lon>-85.834736</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>256</npa>
<nxx>495</nxx>
<x>A</x>
<exch>006590</exch>
<rc>Bridgeport</rc>
<region>AL</region>
<switch>BRPTALMARS2</switch>
<switchname>BRIDGEPORT</switchname>
<switchtype>EXM</switchtype>
<ocn>9419</ocn>
<company-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </company-name>
<company-type>I</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7151</rc-v>
<rc-h>2421</rc-h>
<rc-lat>34.950128</rc-lat>
<rc-lon>-85.723616</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>256</npa>
<nxx>548</nxx>
<x>A</x>
<exch>008980</exch>
<rc>Stevenson</rc>
<region>AL</region>
<switch>CHTGTNGZ1MD</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6214</ocn>
<company-name>NEW CINGULAR WIRELESS PCS, LLC - GA                       </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7176</rc-v>
<rc-h>2430</rc-h>
<rc-lat>34.869143</rc-lat>
<rc-lon>-85.834736</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>256</npa>
<nxx>608</nxx>
<x>A</x>
<exch>008980</exch>
<rc>Stevenson</rc>
<region>AL</region>
<switch>CHTGTNNSX5Y</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6804</ocn>
<company-name>CELLCO PARTNERSHIP DBA VERIZON WIRELESS - AL              </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7176</rc-v>
<rc-h>2430</rc-h>
<rc-lat>34.869143</rc-lat>
<rc-lon>-85.834736</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>256</npa>
<nxx>663</nxx>
<x>A</x>
<exch>008980</exch>
<rc>Stevenson</rc>
<region>AL</region>
<switch>CHTGTNGZ1MD</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6214</ocn>
<company-name>NEW CINGULAR WIRELESS PCS, LLC - GA                       </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7176</rc-v>
<rc-h>2430</rc-h>
<rc-lat>34.869143</rc-lat>
<rc-lon>-85.834736</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>256</npa>
<nxx>670</nxx>
<x>A</x>
<exch>006590</exch>
<rc>Bridgeport</rc>
<region>AL</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>072F</ocn>
<company-name>BANDWIDTH.COM CLEC, LLC - AL                              </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7151</rc-v>
<rc-h>2421</rc-h>
<rc-lat>34.950128</rc-lat>
<rc-lon>-85.723616</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2017-05-05 23:36:25</udate>
</prefixdata>
<prefixdata>
<npa>256</npa>
<nxx>695</nxx>
<x>A</x>
<exch>006590</exch>
<rc>Bridgeport</rc>
<region>AL</region>
<switch>CHTGTNGZ1MD</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6214</ocn>
<company-name>NEW CINGULAR WIRELESS PCS, LLC - GA                       </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7151</rc-v>
<rc-h>2421</rc-h>
<rc-lat>34.950128</rc-lat>
<rc-lon>-85.723616</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>256</npa>
<nxx>703</nxx>
<x>A</x>
<exch>006590</exch>
<rc>Bridgeport</rc>
<region>AL</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>072F</ocn>
<company-name>BANDWIDTH.COM CLEC, LLC - AL                              </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7151</rc-v>
<rc-h>2421</rc-h>
<rc-lat>34.950128</rc-lat>
<rc-lon>-85.723616</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2017-08-01 23:31:15</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>206</nxx>
<x>A</x>
<exch>184110</exch>
<rc>Chattanooga</rc>
<region>TN</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>156J</ocn>
<company-name>RCLEC, INC.                                               </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7098</rc-v>
<rc-h>2366</rc-h>
<rc-lat>35.040869</rc-lat>
<rc-lon>-85.311536</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2018-12-04 01:59:48</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>208</nxx>
<x>A</x>
<exch>184110</exch>
<rc>Chattanooga</rc>
<region>TN</region>
<switch>CHTGTNMAXSX</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6214</ocn>
<company-name>NEW CINGULAR WIRELESS PCS, LLC - GA                       </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7098</rc-v>
<rc-h>2366</rc-h>
<rc-lat>35.040869</rc-lat>
<rc-lon>-85.311536</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>209</nxx>
<x>A</x>
<exch>184110</exch>
<rc>Chattanooga</rc>
<region>TN</region>
<switch>CHTGTNNSDS1</switch>
<switchname>CHATTANOOGA NINTH ST</switchname>
<switchtype>5E</switchtype>
<ocn>9419</ocn>
<company-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </company-name>
<company-type>I</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7098</rc-v>
<rc-h>2366</rc-h>
<rc-lat>35.040869</rc-lat>
<rc-lon>-85.311536</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>216</nxx>
<x>A</x>
<exch>183850</exch>
<rc>Benton</rc>
<region>TN</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>4622</ocn>
<company-name>DELTACOM, INC. - TN                                       </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7015</rc-v>
<rc-h>2278</rc-h>
<rc-lat>35.175527</rc-lat>
<rc-lon>-84.655165</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2019-06-26 02:15:59</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>219</nxx>
<x>A</x>
<exch>184090</exch>
<rc>Charleston</rc>
<region>TN</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>114F</ocn>
<company-name>TELEPORT COMMUNICATIONS AMERICA, LLC - TN                 </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7004</rc-v>
<rc-h>2306</rc-h>
<rc-lat>35.283246</rc-lat>
<rc-lon>-84.76153</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2019-10-09 01:49:53</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>221</nxx>
<x>A</x>
<exch>184110</exch>
<rc>Chattanooga</rc>
<region>TN</region>
<switch>CHTGTNBRDS0</switch>
<switchname>CHATTANOOGA BRAINERD</switchname>
<switchtype>5E</switchtype>
<ocn>6630</ocn>
<company-name>USA MOBILITY WIRELESS, INC.                               </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7098</rc-v>
<rc-h>2366</rc-h>
<rc-lat>35.040869</rc-lat>
<rc-lon>-85.311536</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>225</nxx>
<x>A</x>
<exch>183850</exch>
<rc>Benton</rc>
<region>TN</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>4806</ocn>
<company-name>LEVEL 3 COMMUNICATIONS, LLC - TN                          </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7015</rc-v>
<rc-h>2278</rc-h>
<rc-lat>35.175527</rc-lat>
<rc-lon>-84.655165</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2018-03-23 02:25:18</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>227</nxx>
<x>A</x>
<exch>184110</exch>
<rc>Chattanooga</rc>
<region>TN</region>
<switch>CHTGTNOXEMD</switch>
<switchname></switchname>
<switchtype>POI</switchtype>
<ocn>7473</ocn>
<company-name>POWERTEL ATLANTA LICENSES, INC.                           </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7098</rc-v>
<rc-h>2366</rc-h>
<rc-lat>35.040869</rc-lat>
<rc-lon>-85.311536</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>228</nxx>
<x>A</x>
<exch>186570</exch>
<rc>South Pittsburg</rc>
<region>TN</region>
<switch>CHTGTNKFDS0</switch>
<switchname></switchname>
<switchtype>5E2</switchtype>
<ocn>8356</ocn>
<company-name>US LEC OF TENNESSEE, INC                                  </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7141</rc-v>
<rc-h>2425</rc-h>
<rc-lat>34.999428</rc-lat>
<rc-lon>-85.7163</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>236</nxx>
<x>A</x>
<exch>183700</exch>
<rc>Apison</rc>
<region>TN</region>
<switch>APSNTNXARS5</switch>
<switchname>APISON</switchname>
<switchtype>DCL</switchtype>
<ocn>0574</ocn>
<company-name>CENTURYTEL OOLTEWAH-COLLEGEDALE DBA CENTURYLINK           </company-name>
<company-type>I</company-type>
<ilec-ocn>0574</ilec-ocn>
<ilec-name>CENTURYTEL OOLTEWAH-COLLEGEDALE DBA CENTURYLINK           </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7076</rc-v>
<rc-h>2320</rc-h>
<rc-lat>35.025815</rc-lat>
<rc-lon>-85.027114</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>238</nxx>
<x>A</x>
<exch>186010</exch>
<rc>Ooltewah</rc>
<region>TN</region>
<switch>OLTWTNXADS1</switch>
<switchname>OOLTEWAH</switchname>
<switchtype>DMH</switchtype>
<ocn>0574</ocn>
<company-name>CENTURYTEL OOLTEWAH-COLLEGEDALE DBA CENTURYLINK           </company-name>
<company-type>I</company-type>
<ilec-ocn>0574</ilec-ocn>
<ilec-name>CENTURYTEL OOLTEWAH-COLLEGEDALE DBA CENTURYLINK           </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7069</rc-v>
<rc-h>2330</rc-h>
<rc-lat>35.076524</rc-lat>
<rc-lon>-85.056817</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>240</nxx>
<x>A</x>
<exch>184110</exch>
<rc>Chattanooga</rc>
<region>TN</region>
<switch>CHTGTNNSX1X</switch>
<switchname></switchname>
<switchtype>POI</switchtype>
<ocn>6673</ocn>
<company-name>CELLCO PARTNERSHIP DBA VERIZON WIRELESS - TN              </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7098</rc-v>
<rc-h>2366</rc-h>
<rc-lat>35.040869</rc-lat>
<rc-lon>-85.311536</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>241</nxx>
<x>A</x>
<exch>184320</exch>
<rc>Copper Basin</rc>
<region>TN</region>
<switch>CHTGTNNSX1X</switch>
<switchname></switchname>
<switchtype>POI</switchtype>
<ocn>6673</ocn>
<company-name>CELLCO PARTNERSHIP DBA VERIZON WIRELESS - TN              </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7027</rc-v>
<rc-h>2214</rc-h>
<rc-lat>34.981591</rc-lat>
<rc-lon>-84.376816</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>242</nxx>
<x>A</x>
<exch>184110</exch>
<rc>Chattanooga</rc>
<region>TN</region>
<switch>CHTGTNKVDS0</switch>
<switchname></switchname>
<switchtype>DMH</switchtype>
<ocn>114F</ocn>
<company-name>TELEPORT COMMUNICATIONS AMERICA, LLC - TN                 </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7098</rc-v>
<rc-h>2366</rc-h>
<rc-lat>35.040869</rc-lat>
<rc-lon>-85.311536</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>243</nxx>
<x>A</x>
<exch>186480</exch>
<rc>Soddy Daisy</rc>
<region>TN</region>
<switch>CHTGTNKVDS0</switch>
<switchname></switchname>
<switchtype>DMH</switchtype>
<ocn>114F</ocn>
<company-name>TELEPORT COMMUNICATIONS AMERICA, LLC - TN                 </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7049</rc-v>
<rc-h>2368</rc-h>
<rc-lat>35.242613</rc-lat>
<rc-lon>-85.188001</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>244</nxx>
<x>A</x>
<exch>184180</exch>
<rc>Cleveland</rc>
<region>TN</region>
<switch>CHTGTNKVDS0</switch>
<switchname></switchname>
<switchtype>DMH</switchtype>
<ocn>114F</ocn>
<company-name>TELEPORT COMMUNICATIONS AMERICA, LLC - TN                 </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7037</rc-v>
<rc-h>2309</rc-h>
<rc-lat>35.157614</rc-lat>
<rc-lon>-84.866815</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>250</nxx>
<x>A</x>
<exch>184180</exch>
<rc>Cleveland</rc>
<region>TN</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>204G</ocn>
<company-name>TWIN LAKES COMMUNICATIONS, INC. - TN                      </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7037</rc-v>
<rc-h>2309</rc-h>
<rc-lat>35.157614</rc-lat>
<rc-lon>-84.866815</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2017-05-05 23:36:25</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>255</nxx>
<x>A</x>
<exch>184110</exch>
<rc>Chattanooga</rc>
<region>TN</region>
<switch>CHTGTNOXEMD</switch>
<switchname></switchname>
<switchtype>POI</switchtype>
<ocn>7473</ocn>
<company-name>POWERTEL ATLANTA LICENSES, INC.                           </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7098</rc-v>
<rc-h>2366</rc-h>
<rc-lat>35.040869</rc-lat>
<rc-lon>-85.311536</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>260</nxx>
<x>A</x>
<exch>184110</exch>
<rc>Chattanooga</rc>
<region>TN</region>
<switch>CHTGTNNSX1X</switch>
<switchname></switchname>
<switchtype>POI</switchtype>
<ocn>6673</ocn>
<company-name>CELLCO PARTNERSHIP DBA VERIZON WIRELESS - TN              </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7098</rc-v>
<rc-h>2366</rc-h>
<rc-lat>35.040869</rc-lat>
<rc-lon>-85.311536</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>265</nxx>
<x>A</x>
<exch>184110</exch>
<rc>Chattanooga</rc>
<region>TN</region>
<switch>CHTGTNNSDS1</switch>
<switchname>CHATTANOOGA NINTH ST</switchname>
<switchtype>5E</switchtype>
<ocn>9419</ocn>
<company-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </company-name>
<company-type>I</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7098</rc-v>
<rc-h>2366</rc-h>
<rc-lat>35.040869</rc-lat>
<rc-lon>-85.311536</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>266</nxx>
<x>A</x>
<exch>184110</exch>
<rc>Chattanooga</rc>
<region>TN</region>
<switch>CHTGTNNSDS1</switch>
<switchname>CHATTANOOGA NINTH ST</switchname>
<switchtype>5E</switchtype>
<ocn>9419</ocn>
<company-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </company-name>
<company-type>I</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7098</rc-v>
<rc-h>2366</rc-h>
<rc-lat>35.040869</rc-lat>
<rc-lon>-85.311536</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>267</nxx>
<x>A</x>
<exch>184110</exch>
<rc>Chattanooga</rc>
<region>TN</region>
<switch>CHTGTNNSDS1</switch>
<switchname>CHATTANOOGA NINTH ST</switchname>
<switchtype>5E</switchtype>
<ocn>9419</ocn>
<company-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </company-name>
<company-type>I</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7098</rc-v>
<rc-h>2366</rc-h>
<rc-lat>35.040869</rc-lat>
<rc-lon>-85.311536</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>269</nxx>
<x>A</x>
<exch>184110</exch>
<rc>Chattanooga</rc>
<region>TN</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6673</ocn>
<company-name>CELLCO PARTNERSHIP DBA VERIZON WIRELESS - TN              </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7098</rc-v>
<rc-h>2366</rc-h>
<rc-lat>35.040869</rc-lat>
<rc-lon>-85.311536</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2017-05-05 23:36:25</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>275</nxx>
<x>A</x>
<exch>184110</exch>
<rc>Chattanooga</rc>
<region>TN</region>
<switch>CHTGTNBRDS0</switch>
<switchname>CHATTANOOGA BRAINERD</switchname>
<switchtype>5E</switchtype>
<ocn>6435</ocn>
<company-name>PAGER ONE OF FLORIDA - TENNESSEE                          </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7098</rc-v>
<rc-h>2366</rc-h>
<rc-lat>35.040869</rc-lat>
<rc-lon>-85.311536</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>280</nxx>
<x>A</x>
<exch>184110</exch>
<rc>Chattanooga</rc>
<region>TN</region>
<switch>CHTGTNNSX1X</switch>
<switchname></switchname>
<switchtype>POI</switchtype>
<ocn>6673</ocn>
<company-name>CELLCO PARTNERSHIP DBA VERIZON WIRELESS - TN              </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7098</rc-v>
<rc-h>2366</rc-h>
<rc-lat>35.040869</rc-lat>
<rc-lon>-85.311536</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>284</nxx>
<x>A</x>
<exch>184180</exch>
<rc>Cleveland</rc>
<region>TN</region>
<switch>CHTGTNMAXSX</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6214</ocn>
<company-name>NEW CINGULAR WIRELESS PCS, LLC - GA                       </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7037</rc-v>
<rc-h>2309</rc-h>
<rc-lat>35.157614</rc-lat>
<rc-lon>-84.866815</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>285</nxx>
<x>A</x>
<exch>184450</exch>
<rc>Dayton</rc>
<region>TN</region>
<switch>CHTGTNMAXSX</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6214</ocn>
<company-name>NEW CINGULAR WIRELESS PCS, LLC - GA                       </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>6987</rc-v>
<rc-h>2368</rc-h>
<rc-lat>35.491901</rc-lat>
<rc-lon>-85.018232</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>287</nxx>
<x>A</x>
<exch>184110</exch>
<rc>Chattanooga</rc>
<region>TN</region>
<switch>CHTGTNNSDS1</switch>
<switchname>CHATTANOOGA NINTH ST</switchname>
<switchtype>5E</switchtype>
<ocn>9419</ocn>
<company-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </company-name>
<company-type>I</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7098</rc-v>
<rc-h>2366</rc-h>
<rc-lat>35.040869</rc-lat>
<rc-lon>-85.311536</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>290</nxx>
<x>A</x>
<exch>184110</exch>
<rc>Chattanooga</rc>
<region>TN</region>
<switch>CHTGTNNSX1X</switch>
<switchname></switchname>
<switchtype>POI</switchtype>
<ocn>6673</ocn>
<company-name>CELLCO PARTNERSHIP DBA VERIZON WIRELESS - TN              </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7098</rc-v>
<rc-h>2366</rc-h>
<rc-lat>35.040869</rc-lat>
<rc-lon>-85.311536</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>294</nxx>
<x>A</x>
<exch>184110</exch>
<rc>Chattanooga</rc>
<region>TN</region>
<switch>CHTGTN78DS0</switch>
<switchname></switchname>
<switchtype>5E</switchtype>
<ocn>2757</ocn>
<company-name>CENTURYTEL ACQ LLC DBA CENTURYLINK ACQUISITION TN         </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>472</lata>
<lir></lir>
<rc-v>7098</rc-v>
<rc-h>2366</rc-h>
<rc-lat>35.040869</rc-lat>
<rc-lon>-85.311536</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>423</npa>
<nxx>296</nxx>
<x>A</x>
<exch>184110</exch>
<rc>Chattanooga</rc>
<region>TN</region>
<switch>CHTGTNBRDS0</switch>