<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [
<!ENTITY Aacute           "&#x000C1;" >
<!ENTITY aacute           "&#x000E1;" >
<!ENTITY Acirc            "&#x000C2;" >
<!ENTITY acirc            "&#x000E2;" >
<!ENTITY acute            "&#x000B4;" >
<!ENTITY AElig            "&#x000C6;" >
<!ENTITY aelig            "&#x000E6;" >
<!ENTITY Agrave           "&#x000C0;" >
<!ENTITY agrave           "&#x000E0;" >
<!ENTITY Aring            "&#x000C5;" >
<!ENTITY aring            "&#x000E5;" >
<!ENTITY Atilde           "&#x000C3;" >
<!ENTITY atilde           "&#x000E3;" >
<!ENTITY Auml             "&#x000C4;" >
<!ENTITY auml             "&#x000E4;" >
<!ENTITY brvbar           "&#x000A6;" >
<!ENTITY Ccedil           "&#x000C7;" >
<!ENTITY ccedil           "&#x000E7;" >
<!ENTITY cedil            "&#x000B8;" >
<!ENTITY cent             "&#x000A2;" >
<!ENTITY copy             "&#x000A9;" >
<!ENTITY curren           "&#x000A4;" >
<!ENTITY deg              "&#x000B0;" >
<!ENTITY divide           "&#x000F7;" >
<!ENTITY Eacute           "&#x000C9;" >
<!ENTITY eacute           "&#x000E9;" >
<!ENTITY Ecirc            "&#x000CA;" >
<!ENTITY ecirc            "&#x000EA;" >
<!ENTITY Egrave           "&#x000C8;" >
<!ENTITY egrave           "&#x000E8;" >
<!ENTITY ETH              "&#x000D0;" >
<!ENTITY eth              "&#x000F0;" >
<!ENTITY Euml             "&#x000CB;" >
<!ENTITY euml             "&#x000EB;" >
<!ENTITY frac12           "&#x000BD;" >
<!ENTITY frac14           "&#x000BC;" >
<!ENTITY frac34           "&#x000BE;" >
<!ENTITY Iacute           "&#x000CD;" >
<!ENTITY iacute           "&#x000ED;" >
<!ENTITY Icirc            "&#x000CE;" >
<!ENTITY icirc            "&#x000EE;" >
<!ENTITY iexcl            "&#x000A1;" >
<!ENTITY Igrave           "&#x000CC;" >
<!ENTITY igrave           "&#x000EC;" >
<!ENTITY iquest           "&#x000BF;" >
<!ENTITY Iuml             "&#x000CF;" >
<!ENTITY iuml             "&#x000EF;" >
<!ENTITY laquo            "&#x000AB;" >
<!ENTITY macr             "&#x000AF;" >
<!ENTITY micro            "&#x000B5;" >
<!ENTITY middot           "&#x000B7;" >
<!ENTITY nbsp             "&#x000A0;" >
<!ENTITY not              "&#x000AC;" >
<!ENTITY Ntilde           "&#x000D1;" >
<!ENTITY ntilde           "&#x000F1;" >
<!ENTITY Oacute           "&#x000D3;" >
<!ENTITY oacute           "&#x000F3;" >
<!ENTITY Ocirc            "&#x000D4;" >
<!ENTITY ocirc            "&#x000F4;" >
<!ENTITY Ograve           "&#x000D2;" >
<!ENTITY ograve           "&#x000F2;" >
<!ENTITY ordf             "&#x000AA;" >
<!ENTITY ordm             "&#x000BA;" >
<!ENTITY Oslash           "&#x000D8;" >
<!ENTITY oslash           "&#x000F8;" >
<!ENTITY Otilde           "&#x000D5;" >
<!ENTITY otilde           "&#x000F5;" >
<!ENTITY Ouml             "&#x000D6;" >
<!ENTITY ouml             "&#x000F6;" >
<!ENTITY para             "&#x000B6;" >
<!ENTITY plusmn           "&#x000B1;" >
<!ENTITY pound            "&#x000A3;" >
<!ENTITY raquo            "&#x000BB;" >
<!ENTITY reg              "&#x000AE;" >
<!ENTITY sect             "&#x000A7;" >
<!ENTITY shy              "&#x000AD;" >
<!ENTITY sup1             "&#x000B9;" >
<!ENTITY sup2             "&#x000B2;" >
<!ENTITY sup3             "&#x000B3;" >
<!ENTITY szlig            "&#x000DF;" >
<!ENTITY THORN            "&#x000DE;" >
<!ENTITY thorn            "&#x000FE;" >
<!ENTITY times            "&#x000D7;" >
<!ENTITY Uacute           "&#x000DA;" >
<!ENTITY uacute           "&#x000FA;" >
<!ENTITY Ucirc            "&#x000DB;" >
<!ENTITY ucirc            "&#x000FB;" >
<!ENTITY Ugrave           "&#x000D9;" >
<!ENTITY ugrave           "&#x000F9;" >
<!ENTITY uml              "&#x000A8;" >
<!ENTITY Uuml             "&#x000DC;" >
<!ENTITY uuml             "&#x000FC;" >
<!ENTITY Yacute           "&#x000DD;" >
<!ENTITY yacute           "&#x000FD;" >
<!ENTITY yen              "&#x000A5;" >
<!ENTITY yuml             "&#x000FF;" >
<!ELEMENT root         (inputdata,prefixdata*,error*)>
<!ELEMENT error         (#PCDATA)>
<!ELEMENT inputdata    (npa?,nxx?,x?,exch?,rc?,region?,switch?,lata?,lir?,ocn?,blocks?,pastdays?,nextdays?,udate?)>
<!ELEMENT prefixdata   (npa,nxx,x,exch,udate,rc,region,switch,switchname,switchtype,lata,lir,ocn,company-name,ilec-ocn,ilec-name,rc-v,rc-h,rc-lat,rc-lon,effdate,discdate)>
<!ELEMENT npa          (#PCDATA)>
<!ELEMENT nxx          (#PCDATA)>
<!ELEMENT x            (#PCDATA)>
<!ELEMENT exch         (#PCDATA)>
<!ELEMENT udate        (#PCDATA)>
<!ELEMENT rc           (#PCDATA)>
<!ELEMENT region       (#PCDATA)>
<!ELEMENT switch       (#PCDATA)>
<!ELEMENT switchname   (#PCDATA)>
<!ELEMENT switchtype   (#PCDATA)>
<!ELEMENT lata         (#PCDATA)>
<!ELEMENT lir          (#PCDATA)>
<!ELEMENT ocn          (#PCDATA)>
<!ELEMENT company-name (#PCDATA)>
<!ELEMENT company-type (#PCDATA)>
<!ELEMENT ilec-ocn     (#PCDATA)>
<!ELEMENT ilec-name    (#PCDATA)>
<!ELEMENT rc-v         (#PCDATA)>
<!ELEMENT rc-h         (#PCDATA)>
<!ELEMENT rc-lat       (#PCDATA)>
<!ELEMENT rc-lon       (#PCDATA)>
<!ELEMENT effdate      (#PCDATA)>
<!ELEMENT discdate     (#PCDATA)>
]>
<root>
<inputdata>
<lata>330</lata>
</inputdata>
<prefixdata>
<npa>812</npa>
<nxx>202</nxx>
<x>A</x>
<exch>056300</exch>
<rc>Boonville</rc>
<region>IN</region>
<switch>CHNDINAACM2</switch>
<switchname></switchname>
<switchtype>CMC</switchtype>
<ocn>6725</ocn>
<company-name>CELLCO PARTNERSHIP DBA VERIZON WIRELESS - IN              </company-name>
<company-type>W</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6690</rc-v>
<rc-h>2981</rc-h>
<rc-lat>38.051541</rc-lat>
<rc-lon>-87.276868</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>204</nxx>
<x>A</x>
<exch>057290</exch>
<rc>Evansville</rc>
<region>IN</region>
<switch>EVVLIN03X5X</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6214</ocn>
<company-name>NEW CINGULAR WIRELESS PCS, LLC - GA                       </company-name>
<company-type>W</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6729</rc-v>
<rc-h>3020</rc-h>
<rc-lat>37.976894</rc-lat>
<rc-lon>-87.583565</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>205</nxx>
<x>A</x>
<exch>057290</exch>
<rc>Evansville</rc>
<region>IN</region>
<switch>EVVLIN03X5X</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6214</ocn>
<company-name>NEW CINGULAR WIRELESS PCS, LLC - GA                       </company-name>
<company-type>W</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6729</rc-v>
<rc-h>3020</rc-h>
<rc-lat>37.976894</rc-lat>
<rc-lon>-87.583565</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>213</nxx>
<x>A</x>
<exch>057290</exch>
<rc>Evansville</rc>
<region>IN</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>919G</ocn>
<company-name>METRO FIBERNET, LLC - IN                                  </company-name>
<company-type>C</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6729</rc-v>
<rc-h>3020</rc-h>
<rc-lat>37.976894</rc-lat>
<rc-lon>-87.583565</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2017-10-22 16:34:49</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>214</nxx>
<x>A</x>
<exch>058710</exch>
<rc>McCutchanville</rc>
<region>IN</region>
<switch>EVVLIN01LMD</switch>
<switchname></switchname>
<switchtype>POI</switchtype>
<ocn>7421</ocn>
<company-name>AT&amp;T LOCAL                                                </company-name>
<company-type>C</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6706</rc-v>
<rc-h>3018</rc-h>
<rc-lat>38.066421</rc-lat>
<rc-lon>-87.510613</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>215</nxx>
<x>A</x>
<exch>059800</exch>
<rc>Princeton</rc>
<region>IN</region>
<switch>JSPRINXANMD</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6214</ocn>
<company-name>NEW CINGULAR WIRELESS PCS, LLC - GA                       </company-name>
<company-type>W</company-type>
<ilec-ocn>0779</ilec-ocn>
<ilec-name>FRONTIER NORTH, INC. - IN                                 </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6655</rc-v>
<rc-h>3056</rc-h>
<rc-lat>38.356506</rc-lat>
<rc-lon>-87.566832</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>217</nxx>
<x>A</x>
<exch>056300</exch>
<rc>Boonville</rc>
<region>IN</region>
<switch>EVVLIN03X5X</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6214</ocn>
<company-name>NEW CINGULAR WIRELESS PCS, LLC - GA                       </company-name>
<company-type>W</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6690</rc-v>
<rc-h>2981</rc-h>
<rc-lat>38.051541</rc-lat>
<rc-lon>-87.276868</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>224</nxx>
<x>A</x>
<exch>056990</exch>
<rc>Dale</rc>
<region>IN</region>
<switch>EVVLINLWDS1</switch>
<switchname>EVANSVILLE</switchname>
<switchtype>CSX</switchtype>
<ocn>8934</ocn>
<company-name>WINDSTREAM NORLIGHT, INC. - IN                            </company-name>
<company-type>C</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6643</rc-v>
<rc-h>2950</rc-h>
<rc-lat>38.175311</rc-lat>
<rc-lon>-86.988452</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>228</nxx>
<x>A</x>
<exch>057290</exch>
<rc>Evansville</rc>
<region>IN</region>
<switch>EVVLIN02DS0</switch>
<switchname>EVANSVILLE GREENLEAF</switchname>
<switchtype>DMH</switchtype>
<ocn>9325</ocn>
<company-name>AMERITECH INDIANA                                         </company-name>
<company-type>I</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6729</rc-v>
<rc-h>3020</rc-h>
<rc-lat>37.976894</rc-lat>
<rc-lon>-87.583565</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>247</nxx>
<x>A</x>
<exch>060240</exch>
<rc>Shoals</rc>
<region>IN</region>
<switch>SHLSINXARS0</switch>
<switchname>SHOALS</switchname>
<switchtype>RSC</switchtype>
<ocn>0779</ocn>
<company-name>FRONTIER NORTH, INC. - IN                                 </company-name>
<company-type>I</company-type>
<ilec-ocn>0779</ilec-ocn>
<ilec-name>FRONTIER NORTH, INC. - IN                                 </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6534</rc-v>
<rc-h>2971</rc-h>
<rc-lat>38.665206</rc-lat>
<rc-lon>-86.792955</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>250</nxx>
<x>A</x>
<exch>057290</exch>
<rc>Evansville</rc>
<region>IN</region>
<switch>EVVLIN01JMD</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>7314</ocn>
<company-name>TELEPORT COMMUNICATIONS AMERICA, LLC - IN                 </company-name>
<company-type>C</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6729</rc-v>
<rc-h>3020</rc-h>
<rc-lat>37.976894</rc-lat>
<rc-lon>-87.583565</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>253</nxx>
<x>A</x>
<exch>057290</exch>
<rc>Evansville</rc>
<region>IN</region>
<switch>EVVLINLWDS1</switch>
<switchname>EVANSVILLE</switchname>
<switchtype>CSX</switchtype>
<ocn>8934</ocn>
<company-name>WINDSTREAM NORLIGHT, INC. - IN                            </company-name>
<company-type>C</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6729</rc-v>
<rc-h>3020</rc-h>
<rc-lat>37.976894</rc-lat>
<rc-lon>-87.583565</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>266</nxx>
<x>A</x>
<exch>057290</exch>
<rc>Evansville</rc>
<region>IN</region>
<switch>EVVLIN03WMD</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>105F</ocn>
<company-name>BANDWIDTH.COM CLEC, LLC - IN                              </company-name>
<company-type>C</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6729</rc-v>
<rc-h>3020</rc-h>
<rc-lat>37.976894</rc-lat>
<rc-lon>-87.583565</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>270</nxx>
<x>A</x>
<exch>059220</exch>
<rc>New Harmony</rc>
<region>IN</region>
<switch>CHNDINAACM2</switch>
<switchname></switchname>
<switchtype>CMC</switchtype>
<ocn>6725</ocn>
<company-name>CELLCO PARTNERSHIP DBA VERIZON WIRELESS - IN              </company-name>
<company-type>W</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6726</rc-v>
<rc-h>3088</rc-h>
<rc-lat>38.135274</rc-lat>
<rc-lon>-87.925285</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>295</nxx>
<x>A</x>
<exch>058510</exch>
<rc>Loogootee</rc>
<region>IN</region>
<switch>LOGTINXADS1</switch>
<switchname>LOOGOOTEE</switchname>
<switchtype>DMT</switchtype>
<ocn>0779</ocn>
<company-name>FRONTIER NORTH, INC. - IN                                 </company-name>
<company-type>I</company-type>
<ilec-ocn>0779</ilec-ocn>
<ilec-name>FRONTIER NORTH, INC. - IN                                 </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6541</rc-v>
<rc-h>2989</rc-h>
<rc-lat>38.674371</rc-lat>
<rc-lon>-86.906014</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>296</nxx>
<x>A</x>
<exch>058510</exch>
<rc>Loogootee</rc>
<region>IN</region>
<switch>EVVLINKKBMD</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6534</ocn>
<company-name>NEW CINGULAR WIRELESS PCS, LLC - IL                       </company-name>
<company-type>W</company-type>
<ilec-ocn>0779</ilec-ocn>
<ilec-name>FRONTIER NORTH, INC. - IN                                 </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6541</rc-v>
<rc-h>2989</rc-h>
<rc-lat>38.674371</rc-lat>
<rc-lon>-86.906014</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>297</nxx>
<x>A</x>
<exch>057290</exch>
<rc>Evansville</rc>
<region>IN</region>
<switch>EVVLIN014MD</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>352E</ocn>
<company-name>YMAX COMMUNICATIONS CORP. - IN                            </company-name>
<company-type>C</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6729</rc-v>
<rc-h>3020</rc-h>
<rc-lat>37.976894</rc-lat>
<rc-lon>-87.583565</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>301</nxx>
<x>A</x>
<exch>056990</exch>
<rc>Dale</rc>
<region>IN</region>
<switch>EVVLINLWDS1</switch>
<switchname>EVANSVILLE</switchname>
<switchtype>CSX</switchtype>
<ocn>8934</ocn>
<company-name>WINDSTREAM NORLIGHT, INC. - IN                            </company-name>
<company-type>C</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6643</rc-v>
<rc-h>2950</rc-h>
<rc-lat>38.175311</rc-lat>
<rc-lon>-86.988452</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>303</nxx>
<x>A</x>
<exch>057290</exch>
<rc>Evansville</rc>
<region>IN</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>551D</ocn>
<company-name>TIME WARNER CABLE INFORMATION SVCS (INDIANA) - IN         </company-name>
<company-type>C</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6729</rc-v>
<rc-h>3020</rc-h>
<rc-lat>37.976894</rc-lat>
<rc-lon>-87.583565</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>304</nxx>
<x>A</x>
<exch>059800</exch>
<rc>Princeton</rc>
<region>IN</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6664</ocn>
<company-name>SPRINT SPECTRUM L.P.                                      </company-name>
<company-type>W</company-type>
<ilec-ocn>0779</ilec-ocn>
<ilec-name>FRONTIER NORTH, INC. - IN                                 </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6655</rc-v>
<rc-h>3056</rc-h>
<rc-lat>38.356506</rc-lat>
<rc-lon>-87.566832</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2017-05-05 23:36:25</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>305</nxx>
<x>A</x>
<exch>057290</exch>
<rc>Evansville</rc>
<region>IN</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6664</ocn>
<company-name>SPRINT SPECTRUM L.P.                                      </company-name>
<company-type>W</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6729</rc-v>
<rc-h>3020</rc-h>
<rc-lat>37.976894</rc-lat>
<rc-lon>-87.583565</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2017-05-05 23:36:25</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>306</nxx>
<x>A</x>
<exch>057290</exch>
<rc>Evansville</rc>
<region>IN</region>
<switch>EVVLIN03X5X</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6214</ocn>
<company-name>NEW CINGULAR WIRELESS PCS, LLC - GA                       </company-name>
<company-type>W</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6729</rc-v>
<rc-h>3020</rc-h>
<rc-lat>37.976894</rc-lat>
<rc-lon>-87.583565</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>307</nxx>
<x>A</x>
<exch>059130</exch>
<rc>Mount Vernon</rc>
<region>IN</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6664</ocn>
<company-name>SPRINT SPECTRUM L.P.                                      </company-name>
<company-type>W</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6762</rc-v>
<rc-h>3063</rc-h>
<rc-lat>37.934498</rc-lat>
<rc-lon>-87.89397</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2017-05-05 23:36:25</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>309</nxx>
<x>A</x>
<exch>058050</exch>
<rc>Jasper</rc>
<region>IN</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6664</ocn>
<company-name>SPRINT SPECTRUM L.P.                                      </company-name>
<company-type>W</company-type>
<ilec-ocn>0779</ilec-ocn>
<ilec-name>FRONTIER NORTH, INC. - IN                                 </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6597</rc-v>
<rc-h>2963</rc-h>
<rc-lat>38.390639</rc-lat>
<rc-lon>-86.927787</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2017-05-05 23:36:25</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>315</nxx>
<x>A</x>
<exch>057190</exch>
<rc>Elberfeld</rc>
<region>IN</region>
<switch>EVVLINAPXNX</switch>
<switchname></switchname>
<switchtype>POI</switchtype>
<ocn>4803</ocn>
<company-name>LEVEL 3 COMMUNICATIONS, LLC - IN                          </company-name>
<company-type>C</company-type>
<ilec-ocn>0779</ilec-ocn>
<ilec-name>FRONTIER NORTH, INC. - IN                                 </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6683</rc-v>
<rc-h>3017</rc-h>
<rc-lat>38.158055</rc-lat>
<rc-lon>-87.442608</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>319</nxx>
<x>A</x>
<exch>057290</exch>
<rc>Evansville</rc>
<region>IN</region>
<switch>EVVLIN03X5X</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6214</ocn>
<company-name>NEW CINGULAR WIRELESS PCS, LLC - GA                       </company-name>
<company-type>W</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6729</rc-v>
<rc-h>3020</rc-h>
<rc-lat>37.976894</rc-lat>
<rc-lon>-87.583565</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>326</nxx>
<x>A</x>
<exch>060370</exch>
<rc>St Anthony</rc>
<region>IN</region>
<switch>STATINXARS0</switch>
<switchname>ST ANTHONY</switchname>
<switchtype>1RC</switchtype>
<ocn>0779</ocn>
<company-name>FRONTIER NORTH, INC. - IN                                 </company-name>
<company-type>I</company-type>
<ilec-ocn>0779</ilec-ocn>
<ilec-name>FRONTIER NORTH, INC. - IN                                 </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6604</rc-v>
<rc-h>2939</rc-h>
<rc-lat>38.309692</rc-lat>
<rc-lon>-86.823913</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>338</nxx>
<x>A</x>
<exch>057270</exch>
<rc>English</rc>
<region>IN</region>
<switch>ENGLINXBRS0</switch>
<switchname>ENGLISH</switchname>
<switchtype>RSC</switchtype>
<ocn>0779</ocn>
<company-name>FRONTIER NORTH, INC. - IN                                 </company-name>
<company-type>I</company-type>
<ilec-ocn>0779</ilec-ocn>
<ilec-name>FRONTIER NORTH, INC. - IN                                 </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6570</rc-v>
<rc-h>2886</rc-h>
<rc-lat>38.33104</rc-lat>
<rc-lon>-86.457203</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>351</nxx>
<x>A</x>
<exch>058050</exch>
<rc>Jasper</rc>
<region>IN</region>
<switch>JSPRINXAMMD</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>365C</ocn>
<company-name>POWERTEL KENTUCKY LICENSES, INC.                          </company-name>
<company-type>W</company-type>
<ilec-ocn>0779</ilec-ocn>
<ilec-name>FRONTIER NORTH, INC. - IN                                 </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6597</rc-v>
<rc-h>2963</rc-h>
<rc-lat>38.390639</rc-lat>
<rc-lon>-86.927787</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>357</nxx>
<x>A</x>
<exch>060430</exch>
<rc>St Meinrad</rc>
<region>IN</region>
<switch>SNTCINXADS0</switch>
<switchname>SANTA CLAUS</switchname>
<switchtype>DMT</switchtype>
<ocn>0807</ocn>
<company-name>PERRY - SPENCER RURAL TELEPHONE COOP., INC.               </company-name>
<company-type>I</company-type>
<ilec-ocn>0807</ilec-ocn>
<ilec-name>PERRY - SPENCER RURAL TELEPHONE COOP., INC.               </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6628</rc-v>
<rc-h>2923</rc-h>
<rc-lat>38.177203</rc-lat>
<rc-lon>-86.80848</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>359</nxx>
<x>A</x>
<exch>060120</exch>
<rc>Sandridge</rc>
<region>IN</region>
<switch>SNRGIN01RSK</switch>
<switchname>SANDRIDGE</switchname>
<switchtype>5ER</switchtype>
<ocn>9325</ocn>
<company-name>AMERITECH INDIANA                                         </company-name>
<company-type>I</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6709</rc-v>
<rc-h>2948</rc-h>
<rc-lat>37.902498</rc-lat>
<rc-lon>-87.159875</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>362</nxx>
<x>A</x>
<exch>056680</exch>
<rc>Chrisney</rc>
<region>IN</region>
<switch>CHRSIN01RSH</switch>
<switchname>CHRISNEY</switchname>
<switchtype>5ER</switchtype>
<ocn>9325</ocn>
<company-name>AMERITECH INDIANA                                         </company-name>
<company-type>I</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6677</rc-v>
<rc-h>2940</rc-h>
<rc-lat>38.015262</rc-lat>
<rc-lon>-87.030997</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>367</nxx>
<x>A</x>
<exch>057350</exch>
<rc>Ferdinand</rc>
<region>IN</region>
<switch>FDNDINXARS0</switch>
<switchname>FERDINAND</switchname>
<switchtype>RSC</switchtype>
<ocn>0779</ocn>
<company-name>FRONTIER NORTH, INC. - IN                                 </company-name>
<company-type>I</company-type>
<ilec-ocn>0779</ilec-ocn>
<ilec-name>FRONTIER NORTH, INC. - IN                                 </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6623</rc-v>
<rc-h>2935</rc-h>
<rc-lat>38.223783</rc-lat>
<rc-lon>-86.856136</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>368</nxx>
<x>A</x>
<exch>060280</exch>
<rc>Solitude</rc>
<region>IN</region>
<switch>EVVLINLWDS1</switch>
<switchname>EVANSVILLE</switchname>
<switchtype>CSX</switchtype>
<ocn>8934</ocn>
<company-name>WINDSTREAM NORLIGHT, INC. - IN                            </company-name>
<company-type>C</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6744</rc-v>
<rc-h>3074</rc-h>
<rc-lat>38.031674</rc-lat>
<rc-lon>-87.901892</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>370</nxx>
<x>A</x>
<exch>060400</exch>
<rc>St Joseph</rc>
<region>IN</region>
<switch>EVVLIN030MD</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>516C</ocn>
<company-name>AT&amp;T CORP.                                                </company-name>
<company-type>C</company-type>
<ilec-ocn>9325</ilec-ocn>
<ilec-name>AMERITECH INDIANA                                         </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6710</rc-v>
<rc-h>3038</rc-h>
<rc-lat>38.093242</rc-lat>
<rc-lon>-87.624341</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>385</nxx>
<x>A</x>
<exch>059800</exch>
<rc>Princeton</rc>
<region>IN</region>
<switch>PRTNINXADS0</switch>
<switchname>PRINCETON</switchname>
<switchtype>5EH</switchtype>
<ocn>0779</ocn>
<company-name>FRONTIER NORTH, INC. - IN                                 </company-name>
<company-type>I</company-type>
<ilec-ocn>0779</ilec-ocn>
<ilec-name>FRONTIER NORTH, INC. - IN                                 </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6655</rc-v>
<rc-h>3056</rc-h>
<rc-lat>38.356506</rc-lat>
<rc-lon>-87.566832</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>386</nxx>
<x>A</x>
<exch>059800</exch>
<rc>Princeton</rc>
<region>IN</region>
<switch>PRTNINXADS0</switch>
<switchname>PRINCETON</switchname>
<switchtype>5EH</switchtype>
<ocn>0779</ocn>
<company-name>FRONTIER NORTH, INC. - IN                                 </company-name>
<company-type>I</company-type>
<ilec-ocn>0779</ilec-ocn>
<ilec-name>FRONTIER NORTH, INC. - IN                                 </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6655</rc-v>
<rc-h>3056</rc-h>
<rc-lat>38.356506</rc-lat>
<rc-lon>-87.566832</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>387</nxx>
<x>A</x>
<exch>059800</exch>
<rc>Princeton</rc>
<region>IN</region>
<switch>PRTNINXADS0</switch>
<switchname>PRINCETON</switchname>
<switchtype>5EH</switchtype>
<ocn>0779</ocn>
<company-name>FRONTIER NORTH, INC. - IN                                 </company-name>
<company-type>I</company-type>
<ilec-ocn>0779</ilec-ocn>
<ilec-name>FRONTIER NORTH, INC. - IN                                 </ilec-name>
<lata>330</lata>
<lir></lir>
<rc-v>6655</rc-v>
<rc-h>3056</rc-h>
<rc-lat>38.356506</rc-lat>
<rc-lon>-87.566832</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>812</npa>
<nxx>389</nxx>
<x>A</x>
<exch>056240</exch>
<rc>Birdseye</rc>
<region>IN</region>
<switch>BRDSINXARS0</switch>
<switchname>BIRDSEYE</switchname>