<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [
<!ENTITY Aacute           "&#x000C1;" >
<!ENTITY aacute           "&#x000E1;" >
<!ENTITY Acirc            "&#x000C2;" >
<!ENTITY acirc            "&#x000E2;" >
<!ENTITY acute            "&#x000B4;" >
<!ENTITY AElig            "&#x000C6;" >
<!ENTITY aelig            "&#x000E6;" >
<!ENTITY Agrave           "&#x000C0;" >
<!ENTITY agrave           "&#x000E0;" >
<!ENTITY Aring            "&#x000C5;" >
<!ENTITY aring            "&#x000E5;" >
<!ENTITY Atilde           "&#x000C3;" >
<!ENTITY atilde           "&#x000E3;" >
<!ENTITY Auml             "&#x000C4;" >
<!ENTITY auml             "&#x000E4;" >
<!ENTITY brvbar           "&#x000A6;" >
<!ENTITY Ccedil           "&#x000C7;" >
<!ENTITY ccedil           "&#x000E7;" >
<!ENTITY cedil            "&#x000B8;" >
<!ENTITY cent             "&#x000A2;" >
<!ENTITY copy             "&#x000A9;" >
<!ENTITY curren           "&#x000A4;" >
<!ENTITY deg              "&#x000B0;" >
<!ENTITY divide           "&#x000F7;" >
<!ENTITY Eacute           "&#x000C9;" >
<!ENTITY eacute           "&#x000E9;" >
<!ENTITY Ecirc            "&#x000CA;" >
<!ENTITY ecirc            "&#x000EA;" >
<!ENTITY Egrave           "&#x000C8;" >
<!ENTITY egrave           "&#x000E8;" >
<!ENTITY ETH              "&#x000D0;" >
<!ENTITY eth              "&#x000F0;" >
<!ENTITY Euml             "&#x000CB;" >
<!ENTITY euml             "&#x000EB;" >
<!ENTITY frac12           "&#x000BD;" >
<!ENTITY frac14           "&#x000BC;" >
<!ENTITY frac34           "&#x000BE;" >
<!ENTITY Iacute           "&#x000CD;" >
<!ENTITY iacute           "&#x000ED;" >
<!ENTITY Icirc            "&#x000CE;" >
<!ENTITY icirc            "&#x000EE;" >
<!ENTITY iexcl            "&#x000A1;" >
<!ENTITY Igrave           "&#x000CC;" >
<!ENTITY igrave           "&#x000EC;" >
<!ENTITY iquest           "&#x000BF;" >
<!ENTITY Iuml             "&#x000CF;" >
<!ENTITY iuml             "&#x000EF;" >
<!ENTITY laquo            "&#x000AB;" >
<!ENTITY macr             "&#x000AF;" >
<!ENTITY micro            "&#x000B5;" >
<!ENTITY middot           "&#x000B7;" >
<!ENTITY nbsp             "&#x000A0;" >
<!ENTITY not              "&#x000AC;" >
<!ENTITY Ntilde           "&#x000D1;" >
<!ENTITY ntilde           "&#x000F1;" >
<!ENTITY Oacute           "&#x000D3;" >
<!ENTITY oacute           "&#x000F3;" >
<!ENTITY Ocirc            "&#x000D4;" >
<!ENTITY ocirc            "&#x000F4;" >
<!ENTITY Ograve           "&#x000D2;" >
<!ENTITY ograve           "&#x000F2;" >
<!ENTITY ordf             "&#x000AA;" >
<!ENTITY ordm             "&#x000BA;" >
<!ENTITY Oslash           "&#x000D8;" >
<!ENTITY oslash           "&#x000F8;" >
<!ENTITY Otilde           "&#x000D5;" >
<!ENTITY otilde           "&#x000F5;" >
<!ENTITY Ouml             "&#x000D6;" >
<!ENTITY ouml             "&#x000F6;" >
<!ENTITY para             "&#x000B6;" >
<!ENTITY plusmn           "&#x000B1;" >
<!ENTITY pound            "&#x000A3;" >
<!ENTITY raquo            "&#x000BB;" >
<!ENTITY reg              "&#x000AE;" >
<!ENTITY sect             "&#x000A7;" >
<!ENTITY shy              "&#x000AD;" >
<!ENTITY sup1             "&#x000B9;" >
<!ENTITY sup2             "&#x000B2;" >
<!ENTITY sup3             "&#x000B3;" >
<!ENTITY szlig            "&#x000DF;" >
<!ENTITY THORN            "&#x000DE;" >
<!ENTITY thorn            "&#x000FE;" >
<!ENTITY times            "&#x000D7;" >
<!ENTITY Uacute           "&#x000DA;" >
<!ENTITY uacute           "&#x000FA;" >
<!ENTITY Ucirc            "&#x000DB;" >
<!ENTITY ucirc            "&#x000FB;" >
<!ENTITY Ugrave           "&#x000D9;" >
<!ENTITY ugrave           "&#x000F9;" >
<!ENTITY uml              "&#x000A8;" >
<!ENTITY Uuml             "&#x000DC;" >
<!ENTITY uuml             "&#x000FC;" >
<!ENTITY Yacute           "&#x000DD;" >
<!ENTITY yacute           "&#x000FD;" >
<!ENTITY yen              "&#x000A5;" >
<!ENTITY yuml             "&#x000FF;" >
<!ELEMENT root         (inputdata,prefixdata*,error*)>
<!ELEMENT error         (#PCDATA)>
<!ELEMENT inputdata    (npa?,nxx?,x?,exch?,rc?,region?,switch?,lata?,lir?,ocn?,blocks?,pastdays?,nextdays?,udate?)>
<!ELEMENT prefixdata   (npa,nxx,x,exch,udate,rc,region,switch,switchname,switchtype,lata,lir,ocn,company-name,ilec-ocn,ilec-name,rc-v,rc-h,rc-lat,rc-lon,effdate,discdate)>
<!ELEMENT npa          (#PCDATA)>
<!ELEMENT nxx          (#PCDATA)>
<!ELEMENT x            (#PCDATA)>
<!ELEMENT exch         (#PCDATA)>
<!ELEMENT udate        (#PCDATA)>
<!ELEMENT rc           (#PCDATA)>
<!ELEMENT region       (#PCDATA)>
<!ELEMENT switch       (#PCDATA)>
<!ELEMENT switchname   (#PCDATA)>
<!ELEMENT switchtype   (#PCDATA)>
<!ELEMENT lata         (#PCDATA)>
<!ELEMENT lir          (#PCDATA)>
<!ELEMENT ocn          (#PCDATA)>
<!ELEMENT company-name (#PCDATA)>
<!ELEMENT company-type (#PCDATA)>
<!ELEMENT ilec-ocn     (#PCDATA)>
<!ELEMENT ilec-name    (#PCDATA)>
<!ELEMENT rc-v         (#PCDATA)>
<!ELEMENT rc-h         (#PCDATA)>
<!ELEMENT rc-lat       (#PCDATA)>
<!ELEMENT rc-lon       (#PCDATA)>
<!ELEMENT effdate      (#PCDATA)>
<!ELEMENT discdate     (#PCDATA)>
]>
<root>
<inputdata>
<lata>490</lata>
</inputdata>
<prefixdata>
<npa>504</npa>
<nxx>200</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>NWORLAMTDS2</switch>
<switchname></switchname>
<switchtype>DRM</switchtype>
<ocn>3807</ocn>
<company-name>NETWORK TELEPHONE CORPORATION - LA                        </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>201</nxx>
<x>A</x>
<exch>072590</exch>
<rc>Kenner</rc>
<region>LA</region>
<switch>NWORLAAMCM0</switch>
<switchname></switchname>
<switchtype>AXT</switchtype>
<ocn>6922</ocn>
<company-name>MTPCS, LLC                                                </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8492</rc-v>
<rc-h>2669</rc-h>
<rc-lat>29.973169</rc-lat>
<rc-lon>-90.243206</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>202</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>NWORLAMA01Z</switch>
<switchname></switchname>
<switchtype>POI</switchtype>
<ocn>7421</ocn>
<company-name>AT&amp;T LOCAL                                                </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>205</nxx>
<x>A</x>
<exch>072670</exch>
<rc>Lafitte</rc>
<region>LA</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>5562</ocn>
<company-name>METRO PCS, INC.                                           </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8530</rc-v>
<rc-h>2628</rc-h>
<rc-lat>29.731991</rc-lat>
<rc-lon>-90.136024</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2017-05-05 23:36:25</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>206</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>HMNDLAGWCM1</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6664</ocn>
<company-name>SPRINT SPECTRUM L.P.                                      </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>207</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>NWORLAMODS0</switch>
<switchname></switchname>
<switchtype>5E</switchtype>
<ocn>8660</ocn>
<company-name>NUVOX COMMUNICATIONS                                      </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>208</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>MTRELANJRS0</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>3232</ocn>
<company-name>LEVEL 3 COMMUNICATIONS, LLC - LA                          </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>209</nxx>
<x>A</x>
<exch>072670</exch>
<rc>Lafitte</rc>
<region>LA</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>5562</ocn>
<company-name>METRO PCS, INC.                                           </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8530</rc-v>
<rc-h>2628</rc-h>
<rc-lat>29.731991</rc-lat>
<rc-lon>-90.136024</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2017-05-05 23:36:25</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>210</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>NWORLA23DS2</switch>
<switchname></switchname>
<switchtype>DS</switchtype>
<ocn>4618</ocn>
<company-name>DELTACOM, INC. - LA                                       </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>212</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>NWORLAMODS0</switch>
<switchname></switchname>
<switchtype>5E</switchtype>
<ocn>8660</ocn>
<company-name>NUVOX COMMUNICATIONS                                      </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>213</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>NWORLAMTDS0</switch>
<switchname>NEW ORLEANS METAIRIE</switchname>
<switchtype>5E</switchtype>
<ocn>6630</ocn>
<company-name>USA MOBILITY WIRELESS, INC.                               </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>214</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>MNVLLA20G07</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6214</ocn>
<company-name>NEW CINGULAR WIRELESS PCS, LLC - GA                       </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>215</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>HMNDLAGWCM1</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6664</ocn>
<company-name>SPRINT SPECTRUM L.P.                                      </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>216</nxx>
<x>A</x>
<exch>072590</exch>
<rc>Kenner</rc>
<region>LA</region>
<switch>NWORLAOKDS1</switch>
<switchname></switchname>
<switchtype>5E</switchtype>
<ocn>8839</ocn>
<company-name>ADVANCED TEL INC. - LA                                    </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8492</rc-v>
<rc-h>2669</rc-h>
<rc-lat>29.973169</rc-lat>
<rc-lon>-90.243206</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>217</nxx>
<x>A</x>
<exch>072590</exch>
<rc>Kenner</rc>
<region>LA</region>
<switch>HMNDLAGWCM1</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6664</ocn>
<company-name>SPRINT SPECTRUM L.P.                                      </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8492</rc-v>
<rc-h>2669</rc-h>
<rc-lat>29.973169</rc-lat>
<rc-lon>-90.243206</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>218</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>NWORLASDDS0</switch>
<switchname></switchname>
<switchtype>NT5</switchtype>
<ocn>8764</ocn>
<company-name>INTERMEDIA COMMUNICATIONS INC. - LA                       </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>219</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>NWORLAMTDS0</switch>
<switchname>NEW ORLEANS METAIRIE</switchname>
<switchtype>5E</switchtype>
<ocn>9419</ocn>
<company-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </company-name>
<company-type>I</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>220</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>CVTNLAGOCM1</switch>
<switchname></switchname>
<switchtype>5E2</switchtype>
<ocn>6505</ocn>
<company-name>CELLCO PARTNERSHIP DBA VERIZON WIRELESS - LA              </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>221</nxx>
<x>A</x>
<exch>072590</exch>
<rc>Kenner</rc>
<region>LA</region>
<switch>HMNDLAGWCM1</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6664</ocn>
<company-name>SPRINT SPECTRUM L.P.                                      </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8492</rc-v>
<rc-h>2669</rc-h>
<rc-lat>29.973169</rc-lat>
<rc-lon>-90.243206</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>222</nxx>
<x>A</x>
<exch>072590</exch>
<rc>Kenner</rc>
<region>LA</region>
<switch>HMNDLAGWCM1</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6664</ocn>
<company-name>SPRINT SPECTRUM L.P.                                      </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8492</rc-v>
<rc-h>2669</rc-h>
<rc-lat>29.973169</rc-lat>
<rc-lon>-90.243206</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>223</nxx>
<x>A</x>
<exch>072590</exch>
<rc>Kenner</rc>
<region>LA</region>
<switch>HMNDLAGWCM1</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6664</ocn>
<company-name>SPRINT SPECTRUM L.P.                                      </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8492</rc-v>
<rc-h>2669</rc-h>
<rc-lat>29.973169</rc-lat>
<rc-lon>-90.243206</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>224</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>CVTNLAGOCM1</switch>
<switchname></switchname>
<switchtype>5E2</switchtype>
<ocn>6505</ocn>
<company-name>CELLCO PARTNERSHIP DBA VERIZON WIRELESS - LA              </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>226</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>749E</ocn>
<company-name>ONVOY, LLC - LA                                           </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2017-11-23 01:57:14</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>227</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>NWORLARVDS0</switch>
<switchname>NEW ORLEANS RIVERSIDE</switchname>
<switchtype>DE5</switchtype>
<ocn>9419</ocn>
<company-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </company-name>
<company-type>I</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>228</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>CVTNLAGOCM1</switch>
<switchname></switchname>
<switchtype>5E2</switchtype>
<ocn>6505</ocn>
<company-name>CELLCO PARTNERSHIP DBA VERIZON WIRELESS - LA              </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>229</nxx>
<x>A</x>
<exch>072590</exch>
<rc>Kenner</rc>
<region>LA</region>
<switch>HMNDLAGWCM1</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6664</ocn>
<company-name>SPRINT SPECTRUM L.P.                                      </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8492</rc-v>
<rc-h>2669</rc-h>
<rc-lat>29.973169</rc-lat>
<rc-lon>-90.243206</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>230</nxx>
<x>A</x>
<exch>072590</exch>
<rc>Kenner</rc>
<region>LA</region>
<switch>NWORLAMTXKX</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>150C</ocn>
<company-name>VOICESTREAM GSM I, LLC                                    </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8492</rc-v>
<rc-h>2669</rc-h>
<rc-lat>29.973169</rc-lat>
<rc-lon>-90.243206</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>231</nxx>
<x>A</x>
<exch>072590</exch>
<rc>Kenner</rc>
<region>LA</region>
<switch>HMNDLAGWCM1</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6664</ocn>
<company-name>SPRINT SPECTRUM L.P.                                      </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8492</rc-v>
<rc-h>2669</rc-h>
<rc-lat>29.973169</rc-lat>
<rc-lon>-90.243206</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>232</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>CVTNLAGOCM1</switch>
<switchname></switchname>
<switchtype>5E2</switchtype>
<ocn>6505</ocn>
<company-name>CELLCO PARTNERSHIP DBA VERIZON WIRELESS - LA              </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>233</nxx>
<x>A</x>
<exch>072670</exch>
<rc>Lafitte</rc>
<region>LA</region>
<switch>HRHNLA06DS0</switch>
<switchname></switchname>
<switchtype>NT5</switchtype>
<ocn>7190</ocn>
<company-name>COX LOUISIANA TELECOM , L.L.C.                            </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8530</rc-v>
<rc-h>2628</rc-h>
<rc-lat>29.731991</rc-lat>
<rc-lon>-90.136024</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>234</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>MNVLLA20G07</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6214</ocn>
<company-name>NEW CINGULAR WIRELESS PCS, LLC - GA                       </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>235</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>NWORLAMODC0</switch>
<switchname></switchname>
<switchtype>5E</switchtype>
<ocn>7488</ocn>
<company-name>LEVEL 3 TELECOM OF LOUISIANA, LLC - LA                    </company-name>
<company-type>C</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>236</nxx>
<x>A</x>
<exch>072590</exch>
<rc>Kenner</rc>
<region>LA</region>
<switch>HMNDLAGWCM1</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6664</ocn>
<company-name>SPRINT SPECTRUM L.P.                                      </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8492</rc-v>
<rc-h>2669</rc-h>
<rc-lat>29.973169</rc-lat>
<rc-lon>-90.243206</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>237</nxx>
<x>A</x>
<exch>072590</exch>
<rc>Kenner</rc>
<region>LA</region>
<switch>HMNDLAGWCM1</switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>6664</ocn>
<company-name>SPRINT SPECTRUM L.P.                                      </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8492</rc-v>
<rc-h>2669</rc-h>
<rc-lat>29.973169</rc-lat>
<rc-lon>-90.243206</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>238</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>NWORLA81H01</switch>
<switchname></switchname>
<switchtype>CMC</switchtype>
<ocn>9748</ocn>
<company-name>AMERICAN MESSAGING SERVICES, LLC                          </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>239</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>CVTNLAGOCM1</switch>
<switchname></switchname>
<switchtype>5E2</switchtype>
<ocn>6505</ocn>
<company-name>CELLCO PARTNERSHIP DBA VERIZON WIRELESS - LA              </company-name>
<company-type>W</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>240</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>NWORLASKDS0</switch>
<switchname>NEW ORLEANS SEABROOK</switchname>
<switchtype>5E</switchtype>
<ocn>9419</ocn>
<company-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </company-name>
<company-type>I</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>241</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>NWORLASKDS0</switch>
<switchname>NEW ORLEANS SEABROOK</switchname>
<switchtype>5E</switchtype>
<ocn>9419</ocn>
<company-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </company-name>
<company-type>I</company-type>
<ilec-ocn>9419</ilec-ocn>
<ilec-name>BELLSOUTH TELECOMM INC DBA SOUTH CENTRAL BELL TEL         </ilec-name>
<lata>490</lata>
<lir></lir>
<rc-v>8483</rc-v>
<rc-h>2638</rc-h>
<rc-lat>29.947792</rc-lat>
<rc-lon>-90.075694</rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>504</npa>
<nxx>242</nxx>
<x>A</x>
<exch>073150</exch>
<rc>New Orleans</rc>
<region>LA</region>
<switch>NWORLASKDS0</switch>
<switchname>NEW ORLEANS SEABROOK</switchname>