<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [
<!ENTITY Aacute           "&#x000C1;" >
<!ENTITY aacute           "&#x000E1;" >
<!ENTITY Acirc            "&#x000C2;" >
<!ENTITY acirc            "&#x000E2;" >
<!ENTITY acute            "&#x000B4;" >
<!ENTITY AElig            "&#x000C6;" >
<!ENTITY aelig            "&#x000E6;" >
<!ENTITY Agrave           "&#x000C0;" >
<!ENTITY agrave           "&#x000E0;" >
<!ENTITY Aring            "&#x000C5;" >
<!ENTITY aring            "&#x000E5;" >
<!ENTITY Atilde           "&#x000C3;" >
<!ENTITY atilde           "&#x000E3;" >
<!ENTITY Auml             "&#x000C4;" >
<!ENTITY auml             "&#x000E4;" >
<!ENTITY brvbar           "&#x000A6;" >
<!ENTITY Ccedil           "&#x000C7;" >
<!ENTITY ccedil           "&#x000E7;" >
<!ENTITY cedil            "&#x000B8;" >
<!ENTITY cent             "&#x000A2;" >
<!ENTITY copy             "&#x000A9;" >
<!ENTITY curren           "&#x000A4;" >
<!ENTITY deg              "&#x000B0;" >
<!ENTITY divide           "&#x000F7;" >
<!ENTITY Eacute           "&#x000C9;" >
<!ENTITY eacute           "&#x000E9;" >
<!ENTITY Ecirc            "&#x000CA;" >
<!ENTITY ecirc            "&#x000EA;" >
<!ENTITY Egrave           "&#x000C8;" >
<!ENTITY egrave           "&#x000E8;" >
<!ENTITY ETH              "&#x000D0;" >
<!ENTITY eth              "&#x000F0;" >
<!ENTITY Euml             "&#x000CB;" >
<!ENTITY euml             "&#x000EB;" >
<!ENTITY frac12           "&#x000BD;" >
<!ENTITY frac14           "&#x000BC;" >
<!ENTITY frac34           "&#x000BE;" >
<!ENTITY Iacute           "&#x000CD;" >
<!ENTITY iacute           "&#x000ED;" >
<!ENTITY Icirc            "&#x000CE;" >
<!ENTITY icirc            "&#x000EE;" >
<!ENTITY iexcl            "&#x000A1;" >
<!ENTITY Igrave           "&#x000CC;" >
<!ENTITY igrave           "&#x000EC;" >
<!ENTITY iquest           "&#x000BF;" >
<!ENTITY Iuml             "&#x000CF;" >
<!ENTITY iuml             "&#x000EF;" >
<!ENTITY laquo            "&#x000AB;" >
<!ENTITY macr             "&#x000AF;" >
<!ENTITY micro            "&#x000B5;" >
<!ENTITY middot           "&#x000B7;" >
<!ENTITY nbsp             "&#x000A0;" >
<!ENTITY not              "&#x000AC;" >
<!ENTITY Ntilde           "&#x000D1;" >
<!ENTITY ntilde           "&#x000F1;" >
<!ENTITY Oacute           "&#x000D3;" >
<!ENTITY oacute           "&#x000F3;" >
<!ENTITY Ocirc            "&#x000D4;" >
<!ENTITY ocirc            "&#x000F4;" >
<!ENTITY Ograve           "&#x000D2;" >
<!ENTITY ograve           "&#x000F2;" >
<!ENTITY ordf             "&#x000AA;" >
<!ENTITY ordm             "&#x000BA;" >
<!ENTITY Oslash           "&#x000D8;" >
<!ENTITY oslash           "&#x000F8;" >
<!ENTITY Otilde           "&#x000D5;" >
<!ENTITY otilde           "&#x000F5;" >
<!ENTITY Ouml             "&#x000D6;" >
<!ENTITY ouml             "&#x000F6;" >
<!ENTITY para             "&#x000B6;" >
<!ENTITY plusmn           "&#x000B1;" >
<!ENTITY pound            "&#x000A3;" >
<!ENTITY raquo            "&#x000BB;" >
<!ENTITY reg              "&#x000AE;" >
<!ENTITY sect             "&#x000A7;" >
<!ENTITY shy              "&#x000AD;" >
<!ENTITY sup1             "&#x000B9;" >
<!ENTITY sup2             "&#x000B2;" >
<!ENTITY sup3             "&#x000B3;" >
<!ENTITY szlig            "&#x000DF;" >
<!ENTITY THORN            "&#x000DE;" >
<!ENTITY thorn            "&#x000FE;" >
<!ENTITY times            "&#x000D7;" >
<!ENTITY Uacute           "&#x000DA;" >
<!ENTITY uacute           "&#x000FA;" >
<!ENTITY Ucirc            "&#x000DB;" >
<!ENTITY ucirc            "&#x000FB;" >
<!ENTITY Ugrave           "&#x000D9;" >
<!ENTITY ugrave           "&#x000F9;" >
<!ENTITY uml              "&#x000A8;" >
<!ENTITY Uuml             "&#x000DC;" >
<!ENTITY uuml             "&#x000FC;" >
<!ENTITY Yacute           "&#x000DD;" >
<!ENTITY yacute           "&#x000FD;" >
<!ENTITY yen              "&#x000A5;" >
<!ENTITY yuml             "&#x000FF;" >
<!ELEMENT root         (inputdata,prefixdata*,error*)>
<!ELEMENT error         (#PCDATA)>
<!ELEMENT inputdata    (npa?,nxx?,x?,exch?,rc?,region?,switch?,lata?,lir?,ocn?,blocks?,pastdays?,nextdays?,udate?)>
<!ELEMENT prefixdata   (npa,nxx,x,exch,udate,rc,region,switch,switchname,switchtype,lata,lir,ocn,company-name,ilec-ocn,ilec-name,rc-v,rc-h,rc-lat,rc-lon,effdate,discdate)>
<!ELEMENT npa          (#PCDATA)>
<!ELEMENT nxx          (#PCDATA)>
<!ELEMENT x            (#PCDATA)>
<!ELEMENT exch         (#PCDATA)>
<!ELEMENT udate        (#PCDATA)>
<!ELEMENT rc           (#PCDATA)>
<!ELEMENT region       (#PCDATA)>
<!ELEMENT switch       (#PCDATA)>
<!ELEMENT switchname   (#PCDATA)>
<!ELEMENT switchtype   (#PCDATA)>
<!ELEMENT lata         (#PCDATA)>
<!ELEMENT lir          (#PCDATA)>
<!ELEMENT ocn          (#PCDATA)>
<!ELEMENT company-name (#PCDATA)>
<!ELEMENT company-type (#PCDATA)>
<!ELEMENT ilec-ocn     (#PCDATA)>
<!ELEMENT ilec-name    (#PCDATA)>
<!ELEMENT rc-v         (#PCDATA)>
<!ELEMENT rc-h         (#PCDATA)>
<!ELEMENT rc-lat       (#PCDATA)>
<!ELEMENT rc-lon       (#PCDATA)>
<!ELEMENT effdate      (#PCDATA)>
<!ELEMENT discdate     (#PCDATA)>
]>
<root>
<inputdata>
<lata>884</lata>
</inputdata>
<prefixdata>
<npa>684</npa>
<nxx>248</nxx>
<x>A</x>
<exch>219410</exch>
<rc>American Samoa</rc>
<region>AS</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>071H</ocn>
<company-name>AST TELECOM, LLC - AS                                     </company-name>
<company-type>C</company-type>
<ilec-ocn>3900</ilec-ocn>
<ilec-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </ilec-name>
<lata>884</lata>
<lir></lir>
<rc-v>19964</rc-v>
<rc-h>18300</rc-h>
<rc-lat></rc-lat>
<rc-lon></rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>684</npa>
<nxx>252</nxx>
<x>A</x>
<exch>219410</exch>
<rc>American Samoa</rc>
<region>AS</region>
<switch>ILILAM2200T</switch>
<switchname></switchname>
<switchtype>D12</switchtype>
<ocn>1460</ocn>
<company-name>AMERICAN SAMOA LICENSE, INC.                              </company-name>
<company-type>W</company-type>
<ilec-ocn>3900</ilec-ocn>
<ilec-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </ilec-name>
<lata>884</lata>
<lir></lir>
<rc-v>19964</rc-v>
<rc-h>18300</rc-h>
<rc-lat></rc-lat>
<rc-lon></rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>684</npa>
<nxx>254</nxx>
<x>A</x>
<exch>219410</exch>
<rc>American Samoa</rc>
<region>AS</region>
<switch>ILILAM2200T</switch>
<switchname></switchname>
<switchtype>D12</switchtype>
<ocn>1460</ocn>
<company-name>AMERICAN SAMOA LICENSE, INC.                              </company-name>
<company-type>W</company-type>
<ilec-ocn>3900</ilec-ocn>
<ilec-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </ilec-name>
<lata>884</lata>
<lir></lir>
<rc-v>19964</rc-v>
<rc-h>18300</rc-h>
<rc-lat></rc-lat>
<rc-lon></rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>684</npa>
<nxx>256</nxx>
<x>A</x>
<exch>219410</exch>
<rc>American Samoa</rc>
<region>AS</region>
<switch>ILILAM2200T</switch>
<switchname></switchname>
<switchtype>D12</switchtype>
<ocn>1460</ocn>
<company-name>AMERICAN SAMOA LICENSE, INC.                              </company-name>
<company-type>W</company-type>
<ilec-ocn>3900</ilec-ocn>
<ilec-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </ilec-name>
<lata>884</lata>
<lir></lir>
<rc-v>19964</rc-v>
<rc-h>18300</rc-h>
<rc-lat></rc-lat>
<rc-lon></rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>684</npa>
<nxx>258</nxx>
<x>A</x>
<exch>219410</exch>
<rc>American Samoa</rc>
<region>AS</region>
<switch>ILILAM2200T</switch>
<switchname></switchname>
<switchtype>D12</switchtype>
<ocn>1460</ocn>
<company-name>AMERICAN SAMOA LICENSE, INC.                              </company-name>
<company-type>W</company-type>
<ilec-ocn>3900</ilec-ocn>
<ilec-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </ilec-name>
<lata>884</lata>
<lir></lir>
<rc-v>19964</rc-v>
<rc-h>18300</rc-h>
<rc-lat></rc-lat>
<rc-lon></rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>684</npa>
<nxx>272</nxx>
<x>A</x>
<exch>219410</exch>
<rc>American Samoa</rc>
<region>AS</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>1460</ocn>
<company-name>AMERICAN SAMOA LICENSE, INC.                              </company-name>
<company-type>W</company-type>
<ilec-ocn>3900</ilec-ocn>
<ilec-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </ilec-name>
<lata>884</lata>
<lir></lir>
<rc-v>19964</rc-v>
<rc-h>18300</rc-h>
<rc-lat></rc-lat>
<rc-lon></rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2017-05-05 23:36:25</udate>
</prefixdata>
<prefixdata>
<npa>684</npa>
<nxx>622</nxx>
<x>A</x>
<exch>219410</exch>
<rc>American Samoa</rc>
<region>AS</region>
<switch>FGTAAMAARS0</switch>
<switchname></switchname>
<switchtype>RS</switchtype>
<ocn>3900</ocn>
<company-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </company-name>
<company-type>I</company-type>
<ilec-ocn>3900</ilec-ocn>
<ilec-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </ilec-name>
<lata>884</lata>
<lir></lir>
<rc-v>19964</rc-v>
<rc-h>18300</rc-h>
<rc-lat></rc-lat>
<rc-lon></rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>684</npa>
<nxx>633</nxx>
<x>A</x>
<exch>219410</exch>
<rc>American Samoa</rc>
<region>AS</region>
<switch>FGTGAMAA0GT</switch>
<switchname></switchname>
<switchtype>TDM</switchtype>
<ocn>3900</ocn>
<company-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </company-name>
<company-type>I</company-type>
<ilec-ocn>3900</ilec-ocn>
<ilec-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </ilec-name>
<lata>884</lata>
<lir></lir>
<rc-v>19964</rc-v>
<rc-h>18300</rc-h>
<rc-lat></rc-lat>
<rc-lon></rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>684</npa>
<nxx>644</nxx>
<x>A</x>
<exch>219410</exch>
<rc>American Samoa</rc>
<region>AS</region>
<switch>STALAMAADS1</switch>
<switchname></switchname>
<switchtype>DS</switchtype>
<ocn>3900</ocn>
<company-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </company-name>
<company-type>I</company-type>
<ilec-ocn>3900</ilec-ocn>
<ilec-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </ilec-name>
<lata>884</lata>
<lir></lir>
<rc-v>19964</rc-v>
<rc-h>18300</rc-h>
<rc-lat></rc-lat>
<rc-lon></rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>684</npa>
<nxx>655</nxx>
<x>A</x>
<exch>219410</exch>
<rc>American Samoa</rc>
<region>AS</region>
<switch>OFUUAMAARS0</switch>
<switchname></switchname>
<switchtype>RS</switchtype>
<ocn>3900</ocn>
<company-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </company-name>
<company-type>I</company-type>
<ilec-ocn>3900</ilec-ocn>
<ilec-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </ilec-name>
<lata>884</lata>
<lir></lir>
<rc-v>19964</rc-v>
<rc-h>18300</rc-h>
<rc-lat></rc-lat>
<rc-lon></rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>684</npa>
<nxx>677</nxx>
<x>A</x>
<exch>219410</exch>
<rc>American Samoa</rc>
<region>AS</region>
<switch>TAUUAMAADS0</switch>
<switchname></switchname>
<switchtype>DS</switchtype>
<ocn>3900</ocn>
<company-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </company-name>
<company-type>I</company-type>
<ilec-ocn>3900</ilec-ocn>
<ilec-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </ilec-name>
<lata>884</lata>
<lir></lir>
<rc-v>19964</rc-v>
<rc-h>18300</rc-h>
<rc-lat></rc-lat>
<rc-lon></rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>684</npa>
<nxx>688</nxx>
<x>A</x>
<exch>219410</exch>
<rc>American Samoa</rc>
<region>AS</region>
<switch>LONEAMAARS0</switch>
<switchname></switchname>
<switchtype>RS</switchtype>
<ocn>3900</ocn>
<company-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </company-name>
<company-type>I</company-type>
<ilec-ocn>3900</ilec-ocn>
<ilec-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </ilec-name>
<lata>884</lata>
<lir></lir>
<rc-v>19964</rc-v>
<rc-h>18300</rc-h>
<rc-lat></rc-lat>
<rc-lon></rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>684</npa>
<nxx>691</nxx>
<x>A</x>
<exch>219410</exch>
<rc>American Samoa</rc>
<region>AS</region>
<switch>OLMTAMAARS0</switch>
<switchname></switchname>
<switchtype>RS</switchtype>
<ocn>3900</ocn>
<company-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </company-name>
<company-type>I</company-type>
<ilec-ocn>3900</ilec-ocn>
<ilec-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </ilec-name>
<lata>884</lata>
<lir></lir>
<rc-v>19964</rc-v>
<rc-h>18300</rc-h>
<rc-lat></rc-lat>
<rc-lon></rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>684</npa>
<nxx>699</nxx>
<x>A</x>
<exch>219410</exch>
<rc>American Samoa</rc>
<region>AS</region>
<switch>TFUNAMAMDS0</switch>
<switchname></switchname>
<switchtype>DS</switchtype>
<ocn>3900</ocn>
<company-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </company-name>
<company-type>I</company-type>
<ilec-ocn>3900</ilec-ocn>
<ilec-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </ilec-name>
<lata>884</lata>
<lir></lir>
<rc-v>19964</rc-v>
<rc-h>18300</rc-h>
<rc-lat></rc-lat>
<rc-lon></rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2013-10-12 00:37:30</udate>
</prefixdata>
<prefixdata>
<npa>684</npa>
<nxx>731</nxx>
<x>A</x>
<exch>219410</exch>
<rc>American Samoa</rc>
<region>AS</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>909H</ocn>
<company-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY               </company-name>
<company-type>C</company-type>
<ilec-ocn>3900</ilec-ocn>
<ilec-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </ilec-name>
<lata>884</lata>
<lir></lir>
<rc-v>19964</rc-v>
<rc-h>18300</rc-h>
<rc-lat></rc-lat>
<rc-lon></rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2017-05-05 23:36:25</udate>
</prefixdata>
<prefixdata>
<npa>684</npa>
<nxx>733</nxx>
<x>A</x>
<exch>219410</exch>
<rc>American Samoa</rc>
<region>AS</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>909H</ocn>
<company-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY               </company-name>
<company-type>C</company-type>
<ilec-ocn>3900</ilec-ocn>
<ilec-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </ilec-name>
<lata>884</lata>
<lir></lir>
<rc-v>19964</rc-v>
<rc-h>18300</rc-h>
<rc-lat></rc-lat>
<rc-lon></rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2017-05-05 23:36:25</udate>
</prefixdata>
<prefixdata>
<npa>684</npa>
<nxx>770</nxx>
<x>A</x>
<exch>219410</exch>
<rc>American Samoa</rc>
<region>AS</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>909H</ocn>
<company-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY               </company-name>
<company-type>C</company-type>
<ilec-ocn>3900</ilec-ocn>
<ilec-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </ilec-name>
<lata>884</lata>
<lir></lir>
<rc-v>19964</rc-v>
<rc-h>18300</rc-h>
<rc-lat></rc-lat>
<rc-lon></rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2017-05-05 23:36:25</udate>
</prefixdata>
<prefixdata>
<npa>684</npa>
<nxx>782</nxx>
<x>A</x>
<exch>219410</exch>
<rc>American Samoa</rc>
<region>AS</region>
<switch></switch>
<switchname></switchname>
<switchtype></switchtype>
<ocn>3900</ocn>
<company-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </company-name>
<company-type>I</company-type>
<ilec-ocn>3900</ilec-ocn>
<ilec-name>AMERICAN SAMOA TELECOMMUNICATIONS AUTHORITY ASTCA         </ilec-name>
<lata>884</lata>
<lir></lir>
<rc-v>19964</rc-v>
<rc-h>18300</rc-h>
<rc-lat></rc-lat>
<rc-lon></rc-lon>
<effdate></effdate>
<discdate></discdate>
<udate>2018-11-23 03:37:52</udate>
</prefixdata>
</root>
